apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: longhorn
  valuesFrom:
  - kind: ConfigMap
    name: longhorn-helm-chart-value-overrides
    valuesKey: values.yaml # (1)! This is the default, but best to be explicit for clarity
